resources:
- name: github
  type: git
  source:
    uri: https://petegee:oLgf8,64@github.com/petegee/WebApplication.git
    branch: master

jobs:
- name: build
  plan:
  - get: github
    trigger: true
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hey! Listen!"]